//
// Prerequisites & Installation (https://github.com/asciidoctor/asciidoctor-pdf):
// 
//   ruby 2.0.0+
//   prawn 2.0.0+
//   asciidoctor
//   asciidoctor-pdf 1.5.0.alpha.10
// 
// Build the document:
//
// HTML5
//   $ asciidoctor -b html5 README.adoc
//
// PDF
//   $ asciidoctor-pdf README.adoc
//
= Agile Contents Java backend code challenge README

:doctype: book
:lang: en
:listing-caption: Listing

== Resume and TODO list

A microservice will be implemented using Spring Boot 3.1 and Java 17 to complete the technical test for Agile Conten. The chosen architecture is hexagonal, with H2 as the volatile database. The goal is to develop a modern, scalable, and easily maintainable system.

=== TODO List

Covered objectives:

- Development of the requested endpoints.
- Unit testing of the service layer.
- Implementation of paginated user list retrieval.
- Documentation implementation using OpenAPI / Swagger.
- Implementation of handlers for custom exception handling.
- Input data validation using Spring Validation / Custom input data validation using custom annotations.

Uncovered objectives:

- Implementation of reactive programming and use of R2DBC.
- Expansion of testing to unit testing of the remaining application layers.
- Implementation of integration testing.
- Improvement of Swagger documentation with detailed descriptions of elements and operations.
- Implementation of cache with EhCache.

=== Instructions

Needs a maven installation to build.
Just use 'mvn clean install' to build the application and 'mvn springboot:run' to start it.

== Code challenge

The purpose of the test is to validate your technical and organizational skills. It’s not a big
deal if you can’t finish it, we prefer to have an incomplete clean and functional code than a 
badly organized and “ugly” code. It's OK if you set a maximum duration to the challenge.

You have to use the Java programming language and Spring Boot. Apart from that, it's up to you
how you structure the code and what libraries you use. You may also use any code generation tool
like https://start.spring.io[Spring Initializr] or https://www.jhipster.tech[JHypster].

This repository is dedicated to your code challenge, you are free to use it as it suits you. The
only requirement is that all the code must be available in the master branch once you have
finished. You can also edit this document if you want to incluide any information, like build and
running instructions, that would be useful to us.

Take into account that, after you finish the code challenge, we will review it and then maybe we will ask
you to perform a code review together, just to learn a bit about the project and code structure.

IMPORTANT: We would be glad to answer any questions or hear any suggestions about the code
challenge, so don't hesitate to ask. 

=== Features

The application to develop has to manage a collection of users with the following information:

* Username (unique)
* Name
* Email
* Gender
* Picture (only URL value)

Users will be persisted to a database. You can use any database of your preference, relational or
not. Usage of a memory database or one integrated in the app itself is advised for simplicity.

The application will provide the following JSON web services:

* */api/users/ (GET)*: return the list of all users.
* */api/users/{username}/ (GET)*: return a single user.
* */api/users/ (POST)*: create a user.
* */api/users/{username}/ (PUT)*: update the information of a single user.
* */api/users/{username}/ (DELETE)*: delete a single user.
* */api/users/generate/{number}/ (GET)*: generate a number, provided as a parameter, of random users.
To create the users you have to use the https://randomuser.me[Random User Generator] service. Users
will be added to the collection of existing users.
* */api/users/tree/ (GET)*: return a tree with the users grouped by country, state and city (It can’t be done in database).

Extra optional features (only if you are done with the previous features):

* Unit tests (at least one class).
* Pagination of the users list.
* API documentation using Swagger, Spring REST docs or any other tool.

Please, as an integral part of the challenge, update this document or add another one with the instructions required to build, run or test the project. As an example, if any external database is required, provide the required steps to prepare it beforehand, using docker or any other solution if possible, although using an integrated in memory database is preferred for simplicity.
