# server:
#   ssl:
#     key-store: classpath:jrgcertificate.p12
#     key-store-password: password
#     key-alias: jrgcertificate

spring:
  application:
    name: jrg-techchallenge
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
